package com.fizzware.dramaticdoors.compat.registries;

import com.fizzware.dramaticdoors.DDNames;
import com.fizzware.dramaticdoors.blocks.DDBlocks;
import com.fizzware.dramaticdoors.compat.DDCompatAdvancement;
import com.fizzware.dramaticdoors.compat.DDCompatRecipe;
import com.fizzware.dramaticdoors.compat.DDCompatRegistry;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.properties.BlockSetType;

public class ManyIdeasCompat
{
	public static void registerCompat() {
		registerBlocksItems();
		registerRecipes();
	}
	
	private static void registerBlocksItems() {
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_BAR, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_bar"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_BARREL, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_barrel"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_BRICK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_brick"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_CORRUGATED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_corrugated"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_FACTORY, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_factory"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_glass"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_MODERN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_modern"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_SHIP, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_ship"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_SMOOTH_SANDSTONE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_smooth_sandstone"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_COPPER_STEAMPUNK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_copper_steampunk"), Blocks.IRON_DOOR), BlockSetType.IRON, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_bookshelf"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_DWARF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_dwarf"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_FANTASY, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_fantasy"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_glass"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_LABORATORY, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_laboratory"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_RUSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_rusted"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_SAFE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_safe"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_SHIP, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_ship"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_SPACE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_space"), Blocks.IRON_DOOR), BlockSetType.IRON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_IRON_STONE_BRICK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_iron_stone_brick"), Blocks.IRON_DOOR), BlockSetType.IRON, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_blank")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_bookshelf")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_cassette")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_french")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_frosted")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_glass")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_heart")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_origin")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_rustic")), BlockSetType.OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_OAK_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_oak_shoji")), BlockSetType.OAK, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_blank")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_bookshelf")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_cassette")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_french")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_frosted")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_glass")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_heart")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_origin")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_rustic")), BlockSetType.SPRUCE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_SPRUCE_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_spruce_shoji")), BlockSetType.SPRUCE, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_blank")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_bookshelf")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_cassette")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_french")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_frosted")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_glass")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_heart")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_origin")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_rustic")), BlockSetType.BIRCH, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_BIRCH_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_birch_shoji")), BlockSetType.BIRCH, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_blank")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_bookshelf")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_cassette")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_french")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_frosted")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_glass")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_heart")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_origin")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_rustic")), BlockSetType.JUNGLE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_JUNGLE_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_jungle_shoji")), BlockSetType.JUNGLE, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_blank")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_bookshelf")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_cassette")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_french")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_frosted")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_glass")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_heart")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_origin")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_rustic")), BlockSetType.ACACIA, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_ACACIA_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_acacia_shoji")), BlockSetType.ACACIA, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_blank")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_bookshelf")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_cassette")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_french")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_frosted")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_glass")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_heart")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_origin")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_rustic")), BlockSetType.DARK_OAK, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_DARK_OAK_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_dark_oak_shoji")), BlockSetType.DARK_OAK, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_blank")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_bookshelf")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_cassette")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_french")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_frosted")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_glass")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_heart")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_origin")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_rustic")), BlockSetType.MANGROVE, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_MANGROVE_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_mangrove_shoji")), BlockSetType.MANGROVE, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_blank")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_bookshelf")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_cassette")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_french")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_frosted")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_glass")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_heart")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_origin")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_rustic")), BlockSetType.CRIMSON, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_CRIMSON_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_crimson_shoji")), BlockSetType.CRIMSON, false);

		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_BLANK, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_blank")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_BOOKSHELF, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_bookshelf")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_CASSETTE, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_cassette")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_FRENCH, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_french")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_FROSTED, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_frosted")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_GLASS, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_glass")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_HEART, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_heart")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_ORIGIN, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_origin")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_RUSTIC, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_rustic")), BlockSetType.WARPED, false);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MANYIDEAS_WARPED_SHOJI, null, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("manyideas_doors", "door_warped_shoji")), BlockSetType.WARPED, false);
	}
	
	private static void registerRecipes() {
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_BAR, new ResourceLocation("manyideas_doors", "door_copper_bar"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_BARREL, new ResourceLocation("manyideas_doors", "door_copper_barrel"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_BRICK, new ResourceLocation("manyideas_doors", "door_copper_brick"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_CORRUGATED, new ResourceLocation("manyideas_doors", "door_copper_corrugated"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_FACTORY, new ResourceLocation("manyideas_doors", "door_copper_factory"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_GLASS, new ResourceLocation("manyideas_doors", "door_copper_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_MODERN, new ResourceLocation("manyideas_doors", "door_copper_modern"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_SHIP, new ResourceLocation("manyideas_doors", "door_copper_ship"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_SMOOTH_SANDSTONE, new ResourceLocation("manyideas_doors", "door_copper_smooth_sandstone"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_COPPER_STEAMPUNK, new ResourceLocation("manyideas_doors", "door_copper_steampunk"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_iron_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_DWARF, new ResourceLocation("manyideas_doors", "door_iron_dwarf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_FANTASY, new ResourceLocation("manyideas_doors", "door_iron_fantasy"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_GLASS, new ResourceLocation("manyideas_doors", "door_iron_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_LABORATORY, new ResourceLocation("manyideas_doors", "door_iron_laboratory"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_RUSTED, new ResourceLocation("manyideas_doors", "door_iron_rusted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_SAFE, new ResourceLocation("manyideas_doors", "door_iron_safe"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_SHIP, new ResourceLocation("manyideas_doors", "door_iron_ship"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_SPACE, new ResourceLocation("manyideas_doors", "door_iron_space"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_IRON_STONE_BRICK, new ResourceLocation("manyideas_doors", "door_iron_stone_brick"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_BLANK, new ResourceLocation("manyideas_doors", "door_oak_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_oak_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_CASSETTE, new ResourceLocation("manyideas_doors", "door_oak_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_FRENCH, new ResourceLocation("manyideas_doors", "door_oak_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_FROSTED, new ResourceLocation("manyideas_doors", "door_oak_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_GLASS, new ResourceLocation("manyideas_doors", "door_oak_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_HEART, new ResourceLocation("manyideas_doors", "door_oak_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_ORIGIN, new ResourceLocation("manyideas_doors", "door_oak_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_RUSTIC, new ResourceLocation("manyideas_doors", "door_oak_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_OAK_SHOJI, new ResourceLocation("manyideas_doors", "door_oak_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_BLANK, new ResourceLocation("manyideas_doors", "door_spruce_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_spruce_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_CASSETTE, new ResourceLocation("manyideas_doors", "door_spruce_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_FRENCH, new ResourceLocation("manyideas_doors", "door_spruce_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_FROSTED, new ResourceLocation("manyideas_doors", "door_spruce_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_GLASS, new ResourceLocation("manyideas_doors", "door_spruce_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_HEART, new ResourceLocation("manyideas_doors", "door_spruce_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_ORIGIN, new ResourceLocation("manyideas_doors", "door_spruce_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_RUSTIC, new ResourceLocation("manyideas_doors", "door_spruce_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_SPRUCE_SHOJI, new ResourceLocation("manyideas_doors", "door_spruce_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_BLANK, new ResourceLocation("manyideas_doors", "door_birch_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_birch_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_CASSETTE, new ResourceLocation("manyideas_doors", "door_birch_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_FRENCH, new ResourceLocation("manyideas_doors", "door_birch_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_FROSTED, new ResourceLocation("manyideas_doors", "door_birch_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_GLASS, new ResourceLocation("manyideas_doors", "door_birch_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_HEART, new ResourceLocation("manyideas_doors", "door_birch_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_ORIGIN, new ResourceLocation("manyideas_doors", "door_birch_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_RUSTIC, new ResourceLocation("manyideas_doors", "door_birch_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_BIRCH_SHOJI, new ResourceLocation("manyideas_doors", "door_birch_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_BLANK, new ResourceLocation("manyideas_doors", "door_jungle_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_jungle_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_CASSETTE, new ResourceLocation("manyideas_doors", "door_jungle_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_FRENCH, new ResourceLocation("manyideas_doors", "door_jungle_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_FROSTED, new ResourceLocation("manyideas_doors", "door_jungle_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_GLASS, new ResourceLocation("manyideas_doors", "door_jungle_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_HEART, new ResourceLocation("manyideas_doors", "door_jungle_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_ORIGIN, new ResourceLocation("manyideas_doors", "door_jungle_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_RUSTIC, new ResourceLocation("manyideas_doors", "door_jungle_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_JUNGLE_SHOJI, new ResourceLocation("manyideas_doors", "door_jungle_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_BLANK, new ResourceLocation("manyideas_doors", "door_acacia_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_acacia_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_CASSETTE, new ResourceLocation("manyideas_doors", "door_acacia_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_FRENCH, new ResourceLocation("manyideas_doors", "door_acacia_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_FROSTED, new ResourceLocation("manyideas_doors", "door_acacia_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_GLASS, new ResourceLocation("manyideas_doors", "door_acacia_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_HEART, new ResourceLocation("manyideas_doors", "door_acacia_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_ORIGIN, new ResourceLocation("manyideas_doors", "door_acacia_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_RUSTIC, new ResourceLocation("manyideas_doors", "door_acacia_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_ACACIA_SHOJI, new ResourceLocation("manyideas_doors", "door_acacia_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_BLANK, new ResourceLocation("manyideas_doors", "door_dark_oak_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_dark_oak_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_CASSETTE, new ResourceLocation("manyideas_doors", "door_dark_oak_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_FRENCH, new ResourceLocation("manyideas_doors", "door_dark_oak_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_FROSTED, new ResourceLocation("manyideas_doors", "door_dark_oak_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_GLASS, new ResourceLocation("manyideas_doors", "door_dark_oak_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_HEART, new ResourceLocation("manyideas_doors", "door_dark_oak_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_ORIGIN, new ResourceLocation("manyideas_doors", "door_dark_oak_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_RUSTIC, new ResourceLocation("manyideas_doors", "door_dark_oak_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_DARK_OAK_SHOJI, new ResourceLocation("manyideas_doors", "door_dark_oak_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_BLANK, new ResourceLocation("manyideas_doors", "door_crimson_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_crimson_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_CASSETTE, new ResourceLocation("manyideas_doors", "door_crimson_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_FRENCH, new ResourceLocation("manyideas_doors", "door_crimson_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_FROSTED, new ResourceLocation("manyideas_doors", "door_crimson_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_GLASS, new ResourceLocation("manyideas_doors", "door_crimson_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_HEART, new ResourceLocation("manyideas_doors", "door_crimson_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_ORIGIN, new ResourceLocation("manyideas_doors", "door_crimson_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_RUSTIC, new ResourceLocation("manyideas_doors", "door_crimson_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_CRIMSON_SHOJI, new ResourceLocation("manyideas_doors", "door_crimson_shoji"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_BLANK, new ResourceLocation("manyideas_doors", "door_warped_blank"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_warped_bookshelf"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_CASSETTE, new ResourceLocation("manyideas_doors", "door_warped_cassette"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_FRENCH, new ResourceLocation("manyideas_doors", "door_warped_french"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_FROSTED, new ResourceLocation("manyideas_doors", "door_warped_frosted"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_GLASS, new ResourceLocation("manyideas_doors", "door_warped_glass"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_HEART, new ResourceLocation("manyideas_doors", "door_warped_heart"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_ORIGIN, new ResourceLocation("manyideas_doors", "door_warped_origin"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_RUSTIC, new ResourceLocation("manyideas_doors", "door_warped_rustic"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MANYIDEAS_WARPED_SHOJI, new ResourceLocation("manyideas_doors", "door_warped_shoji"));
		
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_BAR, new ResourceLocation("manyideas_doors", "door_copper_bar"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_BARREL, new ResourceLocation("manyideas_doors", "door_copper_barrel"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_BRICK, new ResourceLocation("manyideas_doors", "door_copper_brick"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_CORRUGATED, new ResourceLocation("manyideas_doors", "door_copper_corrugated"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_FACTORY, new ResourceLocation("manyideas_doors", "door_copper_factory"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_GLASS, new ResourceLocation("manyideas_doors", "door_copper_glass"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_MODERN, new ResourceLocation("manyideas_doors", "door_copper_modern"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_SHIP, new ResourceLocation("manyideas_doors", "door_copper_ship"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_SMOOTH_SANDSTONE, new ResourceLocation("manyideas_doors", "door_copper_smooth_sandstone"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_COPPER_STEAMPUNK, new ResourceLocation("manyideas_doors", "door_copper_steampunk"), "tall_manyideas_copper_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_iron_bookshelf"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_DWARF, new ResourceLocation("manyideas_doors", "door_iron_dwarf"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_FANTASY, new ResourceLocation("manyideas_doors", "door_iron_fantasy"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_GLASS, new ResourceLocation("manyideas_doors", "door_iron_glass"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_LABORATORY, new ResourceLocation("manyideas_doors", "door_iron_laboratory"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_RUSTED, new ResourceLocation("manyideas_doors", "door_iron_rusted"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_SAFE, new ResourceLocation("manyideas_doors", "door_iron_safe"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_SHIP, new ResourceLocation("manyideas_doors", "door_iron_ship"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_SPACE, new ResourceLocation("manyideas_doors", "door_iron_space"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_IRON_STONE_BRICK, new ResourceLocation("manyideas_doors", "door_iron_stone_brick"), "tall_manyideas_iron_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_BLANK, new ResourceLocation("manyideas_doors", "door_oak_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_oak_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_CASSETTE, new ResourceLocation("manyideas_doors", "door_oak_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_FRENCH, new ResourceLocation("manyideas_doors", "door_oak_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_FROSTED, new ResourceLocation("manyideas_doors", "door_oak_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_GLASS, new ResourceLocation("manyideas_doors", "door_oak_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_HEART, new ResourceLocation("manyideas_doors", "door_oak_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_ORIGIN, new ResourceLocation("manyideas_doors", "door_oak_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_RUSTIC, new ResourceLocation("manyideas_doors", "door_oak_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_OAK_SHOJI, new ResourceLocation("manyideas_doors", "door_oak_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_BLANK, new ResourceLocation("manyideas_doors", "door_spruce_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_spruce_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_CASSETTE, new ResourceLocation("manyideas_doors", "door_spruce_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_FRENCH, new ResourceLocation("manyideas_doors", "door_spruce_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_FROSTED, new ResourceLocation("manyideas_doors", "door_spruce_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_GLASS, new ResourceLocation("manyideas_doors", "door_spruce_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_HEART, new ResourceLocation("manyideas_doors", "door_spruce_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_ORIGIN, new ResourceLocation("manyideas_doors", "door_spruce_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_RUSTIC, new ResourceLocation("manyideas_doors", "door_spruce_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_SPRUCE_SHOJI, new ResourceLocation("manyideas_doors", "door_spruce_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_BLANK, new ResourceLocation("manyideas_doors", "door_birch_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_birch_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_CASSETTE, new ResourceLocation("manyideas_doors", "door_birch_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_FRENCH, new ResourceLocation("manyideas_doors", "door_birch_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_FROSTED, new ResourceLocation("manyideas_doors", "door_birch_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_GLASS, new ResourceLocation("manyideas_doors", "door_birch_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_HEART, new ResourceLocation("manyideas_doors", "door_birch_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_ORIGIN, new ResourceLocation("manyideas_doors", "door_birch_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_RUSTIC, new ResourceLocation("manyideas_doors", "door_birch_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_BIRCH_SHOJI, new ResourceLocation("manyideas_doors", "door_birch_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_BLANK, new ResourceLocation("manyideas_doors", "door_jungle_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_jungle_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_CASSETTE, new ResourceLocation("manyideas_doors", "door_jungle_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_FRENCH, new ResourceLocation("manyideas_doors", "door_jungle_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_FROSTED, new ResourceLocation("manyideas_doors", "door_jungle_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_GLASS, new ResourceLocation("manyideas_doors", "door_jungle_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_HEART, new ResourceLocation("manyideas_doors", "door_jungle_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_ORIGIN, new ResourceLocation("manyideas_doors", "door_jungle_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_RUSTIC, new ResourceLocation("manyideas_doors", "door_jungle_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_JUNGLE_SHOJI, new ResourceLocation("manyideas_doors", "door_jungle_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_BLANK, new ResourceLocation("manyideas_doors", "door_acacia_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_acacia_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_CASSETTE, new ResourceLocation("manyideas_doors", "door_acacia_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_FRENCH, new ResourceLocation("manyideas_doors", "door_acacia_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_FROSTED, new ResourceLocation("manyideas_doors", "door_acacia_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_GLASS, new ResourceLocation("manyideas_doors", "door_acacia_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_HEART, new ResourceLocation("manyideas_doors", "door_acacia_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_ORIGIN, new ResourceLocation("manyideas_doors", "door_acacia_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_RUSTIC, new ResourceLocation("manyideas_doors", "door_acacia_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_ACACIA_SHOJI, new ResourceLocation("manyideas_doors", "door_acacia_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_BLANK, new ResourceLocation("manyideas_doors", "door_dark_oak_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_dark_oak_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_CASSETTE, new ResourceLocation("manyideas_doors", "door_dark_oak_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_FRENCH, new ResourceLocation("manyideas_doors", "door_dark_oak_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_FROSTED, new ResourceLocation("manyideas_doors", "door_dark_oak_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_GLASS, new ResourceLocation("manyideas_doors", "door_dark_oak_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_HEART, new ResourceLocation("manyideas_doors", "door_dark_oak_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_ORIGIN, new ResourceLocation("manyideas_doors", "door_dark_oak_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_RUSTIC, new ResourceLocation("manyideas_doors", "door_dark_oak_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_DARK_OAK_SHOJI, new ResourceLocation("manyideas_doors", "door_dark_oak_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_BLANK, new ResourceLocation("manyideas_doors", "door_crimson_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_crimson_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_CASSETTE, new ResourceLocation("manyideas_doors", "door_crimson_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_FRENCH, new ResourceLocation("manyideas_doors", "door_crimson_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_FROSTED, new ResourceLocation("manyideas_doors", "door_crimson_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_GLASS, new ResourceLocation("manyideas_doors", "door_crimson_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_HEART, new ResourceLocation("manyideas_doors", "door_crimson_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_ORIGIN, new ResourceLocation("manyideas_doors", "door_crimson_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_RUSTIC, new ResourceLocation("manyideas_doors", "door_crimson_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_CRIMSON_SHOJI, new ResourceLocation("manyideas_doors", "door_crimson_shoji"), "tall_manyideas_shoji_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_BLANK, new ResourceLocation("manyideas_doors", "door_warped_blank"), "tall_manyideas_blank_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_BOOKSHELF, new ResourceLocation("manyideas_doors", "door_warped_bookshelf"), "tall_manyideas_bookshelf_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_CASSETTE, new ResourceLocation("manyideas_doors", "door_warped_cassette"), "tall_manyideas_cassette_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_FRENCH, new ResourceLocation("manyideas_doors", "door_warped_french"), "tall_manyideas_french_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_FROSTED, new ResourceLocation("manyideas_doors", "door_warped_frosted"), "tall_manyideas_frosted_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_GLASS, new ResourceLocation("manyideas_doors", "door_warped_glass"), "tall_manyideas_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_HEART, new ResourceLocation("manyideas_doors", "door_warped_heart"), "tall_manyideas_heart_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_ORIGIN, new ResourceLocation("manyideas_doors", "door_warped_origin"), "tall_manyideas_origin_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_RUSTIC, new ResourceLocation("manyideas_doors", "door_warped_rustic"), "tall_manyideas_rustic_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MANYIDEAS_WARPED_SHOJI, new ResourceLocation("manyideas_doors", "door_warped_shoji"), "tall_manyideas_shoji_door");
	}
}
