package com.fizzware.dramaticdoors.compat.registries;

import com.fizzware.dramaticdoors.DDNames;
import com.fizzware.dramaticdoors.blocks.DDBlocks;
import com.fizzware.dramaticdoors.compat.DDCompatAdvancement;
import com.fizzware.dramaticdoors.compat.DDCompatRecipe;
import com.fizzware.dramaticdoors.compat.DDCompatRegistry;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.properties.BlockSetType;

public class MoShizCompat
{
	public static void registerCompat() {
		registerBlocksItems();
		registerRecipes();
	}
	
	private static void registerBlocksItems() {
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_IRON_BAR, DDNames.SHORT_MS_IRON_BAR, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "iron_bar_door"), Blocks.IRON_DOOR), BlockSetType.IRON, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BAMBOO, DDNames.SHORT_MS_BAMBOO, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "bamboo_door")), BlockSetType.BAMBOO, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_CHERRY, DDNames.SHORT_MS_CHERRY, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "cherry_door")), BlockSetType.CHERRY, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GLOWOOD, DDNames.SHORT_MS_GLOWOOD, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "glowood_door")), BlockSetType.WARPED, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_HELLWOOD, DDNames.SHORT_MS_HELLWOOD, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "hellwood_door")), BlockSetType.CRIMSON, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_MAPLE, DDNames.SHORT_MS_MAPLE, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "maple_door")), BlockSetType.OAK, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_SILVERBELL, DDNames.SHORT_MS_SILVERBELL, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "silverebell_door")), BlockSetType.BIRCH, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_TIGERWOOD, DDNames.SHORT_MS_TIGERWOOD, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "tigerwood_door")), BlockSetType.JUNGLE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_WILLOW, DDNames.SHORT_MS_WILLOW, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "willow_door")), BlockSetType.MANGROVE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GLASS, DDNames.SHORT_MS_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_SOUL_GLASS, DDNames.SHORT_MS_SOUL_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "soul_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_TINTED_GLASS, DDNames.SHORT_MS_TINTED_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "tinted_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BLACK_GLASS, DDNames.SHORT_MS_BLACK_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "black_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GREY_GLASS, DDNames.SHORT_MS_GREY_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "grey_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_LIGHT_GREY_GLASS, DDNames.SHORT_MS_LIGHT_GREY_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "light_grey_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_WHITE_GLASS, DDNames.SHORT_MS_WHITE_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "white_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_RED_GLASS, DDNames.SHORT_MS_RED_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "red_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_ORANGE_GLASS, DDNames.SHORT_MS_ORANGE_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "orange_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_YELLOW_GLASS, DDNames.SHORT_MS_YELLOW_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "yellow_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_LIME_GLASS, DDNames.SHORT_MS_LIME_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "lime_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GREEN_GLASS, DDNames.SHORT_MS_GREEN_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "green_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_CYAN_GLASS, DDNames.SHORT_MS_CYAN_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "cyan_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BLUE_GLASS, DDNames.SHORT_MS_BLUE_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "blue_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_PURPLE_GLASS, DDNames.SHORT_MS_PURPLE_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "purple_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_MAGENTA_GLASS, DDNames.SHORT_MS_MAGENTA_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "magenta_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_PINK_GLASS, DDNames.SHORT_MS_PINK_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "pink_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_LIGHT_BLUE_GLASS, DDNames.SHORT_MS_LIGHT_BLUE_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "light_blue_glass_door")), BlockSetType.STONE, true);
		DDCompatRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BROWN_GLASS, DDNames.SHORT_MS_BROWN_GLASS, DDBlocks.getBlockFromResourceLocation(new ResourceLocation("ms", "brown_glass_door")), BlockSetType.STONE, true);
	}
	
	private static void registerRecipes() {
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_IRON_BAR, new ResourceLocation("ms", "iron_bar_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_BAMBOO, new ResourceLocation("ms", "bamboo_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_CHERRY, new ResourceLocation("ms", "cherry_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_GLOWOOD, new ResourceLocation("ms", "glowood_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_HELLWOOD, new ResourceLocation("ms", "hellwood_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_MAPLE, new ResourceLocation("ms", "maple_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_SILVERBELL, new ResourceLocation("ms", "silverbell_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_TIGERWOOD, new ResourceLocation("ms", "tigerwood_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_WILLOW, new ResourceLocation("ms", "willow_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_GLASS, new ResourceLocation("ms", "glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_SOUL_GLASS, new ResourceLocation("ms", "soul_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_TINTED_GLASS, new ResourceLocation("ms", "tinted_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_BLACK_GLASS, new ResourceLocation("ms", "black_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_GREY_GLASS, new ResourceLocation("ms", "grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_LIGHT_GREY_GLASS, new ResourceLocation("ms", "light_grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_WHITE_GLASS, new ResourceLocation("ms", "white_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_RED_GLASS, new ResourceLocation("ms", "red_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_ORANGE_GLASS, new ResourceLocation("ms", "orange_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_YELLOW_GLASS, new ResourceLocation("ms", "yellow_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_LIME_GLASS, new ResourceLocation("ms", "lime_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_GREEN_GLASS, new ResourceLocation("ms", "green_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_CYAN_GLASS, new ResourceLocation("ms", "cyan_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_BLUE_GLASS, new ResourceLocation("ms", "blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_PURPLE_GLASS, new ResourceLocation("ms", "purple_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_MAGENTA_GLASS, new ResourceLocation("ms", "magenta_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_PINK_GLASS, new ResourceLocation("ms", "pink_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_LIGHT_BLUE_GLASS, new ResourceLocation("ms", "light_blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.SHORT_MS_BROWN_GLASS, new ResourceLocation("ms", "brown_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_IRON_BAR, new ResourceLocation("ms", "iron_bar_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_BAMBOO, new ResourceLocation("ms", "bamboo_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_CHERRY, new ResourceLocation("ms", "cherry_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_GLOWOOD, new ResourceLocation("ms", "glowood_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_HELLWOOD, new ResourceLocation("ms", "hellwood_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_MAPLE, new ResourceLocation("ms", "maple_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_SILVERBELL, new ResourceLocation("ms", "silverbell_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_TIGERWOOD, new ResourceLocation("ms", "tigerwood_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_WILLOW, new ResourceLocation("ms", "willow_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_GLASS, new ResourceLocation("ms", "glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_SOUL_GLASS, new ResourceLocation("ms", "soul_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_TINTED_GLASS, new ResourceLocation("ms", "tinted_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_BLACK_GLASS, new ResourceLocation("ms", "black_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_GREY_GLASS, new ResourceLocation("ms", "grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_LIGHT_GREY_GLASS, new ResourceLocation("ms", "light_grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_WHITE_GLASS, new ResourceLocation("ms", "white_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_RED_GLASS, new ResourceLocation("ms", "red_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_ORANGE_GLASS, new ResourceLocation("ms", "orange_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_YELLOW_GLASS, new ResourceLocation("ms", "yellow_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_LIME_GLASS, new ResourceLocation("ms", "lime_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_GREEN_GLASS, new ResourceLocation("ms", "green_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_CYAN_GLASS, new ResourceLocation("ms", "cyan_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_BLUE_GLASS, new ResourceLocation("ms", "blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_PURPLE_GLASS, new ResourceLocation("ms", "purple_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_MAGENTA_GLASS, new ResourceLocation("ms", "magenta_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_PINK_GLASS, new ResourceLocation("ms", "pink_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_LIGHT_BLUE_GLASS, new ResourceLocation("ms", "light_blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancementJson(DDNames.TALL_MS_BROWN_GLASS, new ResourceLocation("ms", "brown_glass_door"));
		
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_IRON_BAR, new ResourceLocation("ms", "iron_bar_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_BAMBOO, new ResourceLocation("ms", "bamboo_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_CHERRY, new ResourceLocation("ms", "cherry_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_GLOWOOD, new ResourceLocation("ms", "glowood_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_HELLWOOD, new ResourceLocation("ms", "hellwood_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_MAPLE, new ResourceLocation("ms", "maple_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_SILVERBELL, new ResourceLocation("ms", "silverbell_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_TIGERWOOD, new ResourceLocation("ms", "tigerwood_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_WILLOW, new ResourceLocation("ms", "willow_door"), true);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_GLASS, new ResourceLocation("ms", "glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_SOUL_GLASS, new ResourceLocation("ms", "soul_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_TINTED_GLASS, new ResourceLocation("ms", "tinted_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_BLACK_GLASS, new ResourceLocation("ms", "black_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_GREY_GLASS, new ResourceLocation("ms", "grey_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_LIGHT_GREY_GLASS, new ResourceLocation("ms", "light_grey_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_WHITE_GLASS, new ResourceLocation("ms", "white_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_RED_GLASS, new ResourceLocation("ms", "red_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_ORANGE_GLASS, new ResourceLocation("ms", "orange_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_YELLOW_GLASS, new ResourceLocation("ms", "yellow_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_LIME_GLASS, new ResourceLocation("ms", "lime_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_GREEN_GLASS, new ResourceLocation("ms", "green_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_CYAN_GLASS, new ResourceLocation("ms", "cyan_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_BLUE_GLASS, new ResourceLocation("ms", "blue_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_PURPLE_GLASS, new ResourceLocation("ms", "purple_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_MAGENTA_GLASS, new ResourceLocation("ms", "magenta_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_PINK_GLASS, new ResourceLocation("ms", "pink_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_LIGHT_BLUE_GLASS, new ResourceLocation("ms", "light_blue_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipeJson(DDNames.SHORT_MS_BROWN_GLASS, new ResourceLocation("ms", "brown_glass_door"), false);
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_IRON_BAR, new ResourceLocation("ms", "iron_bar_door"), "tall_metal_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_BAMBOO, new ResourceLocation("ms", "bamboo_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_CHERRY, new ResourceLocation("ms", "cherry_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_GLOWOOD, new ResourceLocation("ms", "glowood_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_HELLWOOD, new ResourceLocation("ms", "hellwood_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_MAPLE, new ResourceLocation("ms", "maple_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_SILVERBELL, new ResourceLocation("ms", "silverbell_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_TIGERWOOD, new ResourceLocation("ms", "tigerwood_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_WILLOW, new ResourceLocation("ms", "willow_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_GLASS, new ResourceLocation("ms", "glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_SOUL_GLASS, new ResourceLocation("ms", "soul_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_TINTED_GLASS, new ResourceLocation("ms", "tinted_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_BLACK_GLASS, new ResourceLocation("ms", "black_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_GREY_GLASS, new ResourceLocation("ms", "grey_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_LIGHT_GREY_GLASS, new ResourceLocation("ms", "light_grey_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_WHITE_GLASS, new ResourceLocation("ms", "white_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_RED_GLASS, new ResourceLocation("ms", "red_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_ORANGE_GLASS, new ResourceLocation("ms", "orange_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_YELLOW_GLASS, new ResourceLocation("ms", "yellow_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_LIME_GLASS, new ResourceLocation("ms", "lime_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_GREEN_GLASS, new ResourceLocation("ms", "green_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_CYAN_GLASS, new ResourceLocation("ms", "cyan_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_BLUE_GLASS, new ResourceLocation("ms", "blue_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_PURPLE_GLASS, new ResourceLocation("ms", "purple_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_MAGENTA_GLASS, new ResourceLocation("ms", "magenta_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_PINK_GLASS, new ResourceLocation("ms", "pink_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_LIGHT_BLUE_GLASS, new ResourceLocation("ms", "light_blue_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipeJson(DDNames.TALL_MS_BROWN_GLASS, new ResourceLocation("ms", "brown_glass_door"), "tall_glass_door");
	}
}
